name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5

    - name: Install just
      uses: extractions/setup-just@v2

    - name: Run tests
      run: just test

    - name: Run tests with race detection
      run: just test-race
